const assert=require('assert'); const fs=require('fs'); const vm=require('vm'); const path=require('path');
const src=fs.readFileSync(path.join(__dirname,'..','engines/intel.js'),'utf8');
const store={worldFacts:[{id:'fact_fee',key:'fact_fee'}],currents:[],people:{},memory:{facts:[]},evolution:{events:[]}};
const WA={settingsBus:{read(){return {enabled:false,maxLinks:4,maxItems:2};},normalize(r,v){return v;},saveOrThrow(r,v){this.read=()=>v;return {ok:true};}},store:{get(){return store;},transact(fn){fn(store);}}};
global.window={WorldAxis:WA}; vm.runInNewContext(src,{window:global.window,Date,Number,String,Array,Object,isFinite}, {filename:'engines/intel.js'});
const intel=WA.intel;
assert.strictEqual(intel.buildBlock(),'','disabled empty');
assert.strictEqual(intel.addLink({cause:'missing',effect:'debt'}).reason,'unknown-cause');
const link=intel.addLink({cause:'fact_fee',effect:'debt'}); assert.strictEqual(link.ok,true);
assert.strictEqual(intel.explain('debt').causes.join(','),'fact_fee');
intel.setSettings({enabled:true});
const rumor=intel.addIntel('\u963f\u5b81',{claim:'\u8def\u8d39\u88ab\u622a\u7559',source:'\u9152\u9986\u95f2\u8bdd',level:'rumor',about:'debt'});
assert.strictEqual(rumor.ok,true); assert.strictEqual(store.people.p_\u963f\u5b81.knowledge.intel[0].status,'suspected');
const record=intel.addIntel('\u963f\u5b81',{claim:'\u8d26\u518c\u8bb0\u6709\u622a\u7559',source:'\u94f6\u884c\u8d26\u518c',level:'record',about:'debt'});
assert.strictEqual(record.ok,true); assert.strictEqual(store.people.p_\u963f\u5b81.knowledge.intel[1].status,'believed');
assert.strictEqual(intel.visibleTo('\u522b\u4eba','debt').length,0);
const block=intel.buildBlock();
assert.ok(block.includes('fact_fee') && block.includes('\u6000\u7591') && block.includes('\u94f6\u884c\u8d26\u518c'));
console.log('INTEL-V2530: pass');
