const assert=require('assert'); const fs=require('fs'); const vm=require('vm'); const path=require('path');
const src=fs.readFileSync(path.join(__dirname,'..','engines/life.js'),'utf8');
const store={people:{}};
const WA={settingsBus:{read(){return {enabled:false,maxPeople:4,maxItems:2};},normalize(r,v){return v;},saveOrThrow(r,v){this.value=v; this.read=()=>v; return {ok:true};}},store:{get(){return store;},transact(fn){fn(store);}}};
global.window={WorldAxis:WA}; vm.runInNewContext(src,{window:global.window,Date,Number,String,Array,Object,isFinite,Math}, {filename:'engines/life.js'});
const life=WA.life;
assert.strictEqual(life.buildBlock(),'','disabled injection empty');
assert.strictEqual(life.tick({now:1}).reason,'disabled');
life.setSettings({enabled:true});
const goal=life.addGoal('阿宁',{text:'离开家族',prerequisite:'路费',next:''});
assert.strictEqual(goal.ok,true);
store.people.p_阿宁.profile={relations:[{target:'玩家',trust:80,vigilance:10}]};
assert.strictEqual(life.tick({now:2,with:'玩家'}).changed,1);
assert.strictEqual(store.people.p_阿宁.life.lastDecision.action,'ask');
store.people.p_阿宁.profile.relations[0].vigilance=90;
life.tick({now:3,with:'玩家'});
assert.strictEqual(store.people.p_阿宁.life.lastDecision.action,'hide');
const first=life.addSchedule('阿宁',{activity:'值铺',start:10,end:12});
const clash=life.addSchedule('阿宁',{activity:'赴约',start:11,end:13});
assert.strictEqual(first.ok,true); assert.strictEqual(clash.reason,'time-conflict');
const c=life.addCommitment('阿宁',{kind:'promise',target:'玩家',text:'三日后归还路费',due:5});
assert.strictEqual(c.ok,true);
life.tick({now:6,fulfilledIds:[c.id]});
assert.strictEqual(store.people.p_阿宁.life.commitments[0].status,'kept');
const block=life.buildBlock();
assert.ok(block.includes('离开家族') && block.includes('当前选择=keep'));
console.log('LIFE-V2520: pass');
