# -*- coding: utf-8 -*-
"""v2.85.0 收口：把本版条目插到 README「版本历史」最前（历史条目逐字不动）。"""
import io

P = 'README.md'
s = io.open(P, encoding='utf-8').read()
mark = '<b>v2.84.0</b>'
i = s.index(mark)

ENTRY = u'''<b>v2.85.0</b> — <b>注入效率 · 人物自主生活 · 地域与交通（第三十九面：承诺写在源码里，但没有判据问过它）</b>。三处落点，一把专锁（<code>tests/settle-v2850.js</code>，60 项），两向自证（真源码破坏 ⇒ 判据现形 / 原版上判据不假）。<b>全程零新增导出、零新增容器、零新增设置键</b>——成员冻结串 <code>FROZEN2800</code> 三处段逐字不变，出口面 <code>ns= 103 members= 580 chars= 7169</code> 一字未动。
  <b>A4 · 注入优先级面只有 8 个源名（本版最贵的一处）</b>：<code>inject-budget</code> 的 <code>PRIORITY</code> 表承诺「<b>pinned（rank≤2）优先保障、绝不静默丢弃</b>」，而该表只写了 v0.9.3 时代的 <b>8 个源名</b>（近端事件/世界状态/主观记忆/记忆/叙事摘要/世界推演/账本/舆情），注入面却已长到 <b>45 个 distinct source 名</b>（<code>render/inject.js</code> 46 处 push）。逐个取证：8 个旧名全部命中，其余 <b>37 个零命中</b> ⇒ 那条承诺对它们<b>从未生效</b>；而「有源没被声明」在运行时<b>完全不可见</b>——<code>rankOf</code> 对陌生源静默给 <code>DEFAULT_RANK = 6</code>，不报错、不告警、不进任何读数。这正是 v2.56.0 立过的规矩（<b>源面与声明面必须同时增长</b>）在别处的复发：<b>判据长在一边，另一边悄悄长大，红灯不会亮。</b>修法按<b>可替代性</b>分 7 档补齐 45 源（rank1-2 pinned / rank3 因果与记忆主链 / rank4 长期记忆 / rank5 世界骨架 / rank6 推演结构性面 / rank7 物候氛围 / rank8 统计库存），并让 <code>plan()</code> 收集返回 <code>unranked</code>、<code>summaryText</code> 报出未声明计数——<b>把「没被声明」从不可见变成可读</b>。专锁的 C 面更进一步把它做成<b>成类锁</b>：源名从 <code>render/inject.js</code> <b>真源码</b>用 <code>/source:\\s*'([^']+)'/g</code> 抽取，与声明面双向比对（<code>MISS=[] / EXTRA=[]</code>），<b>再漂移必红</b>，不再等下一次人工发现。
  <b>B1 · 人物自主生活两处真缺陷</b>：① <b>推演名单按插入序截断</b>——旧口径 <code>Object.keys(people).slice(0, maxPeople)</code> 让「谁被推演」取决于<b>谁先进场</b>，一个有目标的人插在第 5 位之后<b>永远轮不到</b>（名额被空壳吃干净，而空壳没有 <code>life</code> 行、跑不出任何决策）。改为 <code>basisOf()</code> 计分（goals / commitments / schedule 各计 1）+ <code>.filter(r.n &gt; 0).sort((b.n - a.n) || (a.i - b.i))</code>：<b>有依据者优先，无依据者不占名额</b>，名额不足时以 <code>stat.skipped</code> 留痕（与「他本来没事可做」是两件事）。② <b>单方面宣布的合作被当作已建立的协作</b>——<code>kind === 'cooperation'</code> 只看自己那一行，不看对方回没回应。新增只读对偶检查 <code>reciprocated()</code>（对方须在同事项文本上持有一行 <code>kind:'cooperation'</code> 且 target 指向本人），不成立则降级为 <code>wait / unreciprocated</code>，但<b>承诺本身不被删</b>（事实存在过要留痕，对齐 shadow「共同隐瞒必须双方各持一行」）。判定位置刻意放在「有目标的人走目标路径」<b>之后</b>：<b>协作被回应与否，不该拦住一个本来就有自己目标的人。</b>
  <b>B2 · 地域与交通（两条全是否定式的新边界）</b>：① <b>层级只说明归属、不说明可达</b>——<code>addPlace</code> 支持 <code>parent</code>，但父子之间<b>没登记道路时 <code>reach</code> 必须 <code>reachable:false</code></b>，层级<b>不得</b>被读成「A 走得到 B」。② <b>路走得通 ≠ 现在走得动</b>——<code>addRoad</code> 支持段容量 <code>cap</code>，容量满时 <code>road-crowded</code> 拒收且<b>拒收不落盘</b>（走 <code>stat.faults</code> 观测）。设计上有三处是刻意的：<b>层级落在 place 行、容量落在 road 行</b>（不另开一张表——新开一张就要回答「谁是真源、改了甲忘了乙怎么办」，那是<b>双真源</b>，本仓库零容忍）；<b>缺省参数不是「改成不限」</b>（<code>explicitCap</code> 判定保证「只改耗时」不会顺带抹掉通行量）；<b>容量按段算</b>（各走各的相邻路段不算拥挤）。语义面还补了两处「两态不可分」：已登记地点的「无 → 有」是<b>补全缺失事实</b>（允许，且只许一次——补后即锁），「x → y」才是<b>冲突改写</b>（<code>parent-locked</code> 拒收并写明现有归属）——若把补全也拒掉，<b>一次误登记就永久锁死</b>；本仓库禁的是「静默改写」，不是「不得改写」。
  <b>两处由本仓库既有成类锁当场抓出的问题（都不是纸面推演）</b>：① 6 个新码未归类 ⇒ <code>reject-lock-v2780</code> 红灯；正解不是删码而是补<b>可执行见证</b>（用产品真 API 真跑出来，见证 71 → <b>77</b>）。② <b>拒收后裸 <code>return;</code></b> ⇒ <code>side-effect-lock-v2790</code> 报「站点数 2 vs 白名单 1」——取证确认 <code>parent-locked</code> 当时写在<b>事务内</b>且用裸 <code>return;</code>，而在 <code>transact</code> 里裸 return <b>不等于 false</b>，会<b>照样提交</b>（推进 <code>stateRev</code>、整份落盘）：正是 v2.79.0 治过的那类缺陷。修法是结构性的：把全部层级校验移到<b>事务之前</b>（只读，拒收分支根本不进事务），缝隙从根上消失；环检测留在事务内但改为 <code>return false</code> <b>透明中止</b>。
  <b>本版最该记住的一条：破坏锚点必须落在热路径上</b>。环检测首版写在<b>补全前</b>的只读校验里——那是错的：<code>A∈B</code>、<code>B∈A</code> <b>只在补全那一瞬</b>才可能成立，事务前读的是补全前的旧图，判它等于<b>写一段永不触发的死代码冒充把关</b>。正确位置是「事务前只读判定全部层级校验（<code>self-parent</code> / <code>unknown-parent</code> / <code>parent-locked</code>）+ 事务内补全前判环（<code>parent-cycle</code>）」。
  <b>三条纪律（来自实测，不是口味）</b>：① <b>零新增导出优先</b>——能用既有面的参数与证据面承载的，不新增 promise（<code>parent</code> 落在 place 行、<code>cap</code> 落在 road 行、<code>unranked</code> 落在既有返回值里）。② <b>锚点命中数 != 期望即整体放弃</b>——A4 首跑因 <code>summaryText</code> 结尾缩进（实为 2 空格 <code>  }</code>）锚点 4 命中 0 次，脚本<b>整体放弃、一字节未写入</b>，改对后重跑才落盘。③ <b>归属守卫是双层的，负控制必须打到「没有守卫的实现」</b>——本版专锁首跑 2 处红全在负控制层：只摘事务前那层时，事务内的 <code>return false</code> 仍兜住（<code>reason</code> 变成 <code>store-unavailable</code>、归属没被改），症状不现形；必须<b>两层一起</b>改成「没有守卫的实现」，才是这条判据要抓的「已有归属被静默改写」（为此给负控制加了多锚点破坏 <code>also</code> 与逐锚 N0 判定）。
  <b>门禁</b>：<code>node tests/run.js</code> → <b>通过 7483 / 失败 0</b>（v2.84.0 收口为 <b>7423 / 0</b>；+60 = 本版专锁）；<code>tests/settle-v2850.js</code> → <b>60 / 0</b>；<code>tests/reject-lock-v2780.js</code> → <b>50 / 0</b>；<code>tests/side-effect-lock-v2790.js</code> → <b>23 / 0</b>（裸 <code>return;</code> 站点已消除）；<code>tests/inventory.js</code> → 四类悬空均 0；<code>tests/export-contract.js</code> → <code>ns= 103 members= 580 chars= 7169</code>（<b>逐字未变</b>）；<code>tests/dead-export-gate.js</code> → dead 444 / uiDead 4 / dataOnly 160 / 仅测试 291（未增长）；<code>tests/test-surface-gate.js</code> → 全部通过、孤儿 0。
'''

s = s[:i] + ENTRY + s[i:]
io.open(P, 'w', encoding='utf-8').write(s)
print('README 已插入 v2.85.0 条目；段长 =', len(ENTRY))
for n, l in enumerate(s.split('\n')[74:90], 75):
    print(n, l[:100])
