"use strict";
const path = require("path");
process.chdir(path.resolve(__dirname, ".."));
const sync = require("../tests/ui-gate-sync.js");
var boot = sync.fresh({});
var WA = boot.WA;
var pass = 0, fail = 0;
function ok(name, cond) { if (cond) { pass++; } else { fail++; console.log("FAIL: " + name); } }
WA.aftermath.setSettings({ enabled: true });
WA.region.setSettings({ enabled: true });
WA.region.register("北道", { distanceDays: 5, lane: "road" });
WA.region.register("南门", { distanceDays: 2, lane: "road" });
ok("S1: aftermath loaded", typeof WA.aftermath === "object");
ok("S2: 13 exports", ["getSettings","setSettings","register","repair","inspect","active","pending","view","cancel","buildBlock","diagnose","stat","reset"].every(function (k) { return typeof WA.aftermath[k] === "function"; }));
ok("S3: enabled true", WA.aftermath.getSettings().enabled === true);
var r1 = WA.aftermath.register({ placeId: "北道", eventId: "evt_001", effectType: "damage", description: "道路被落石阻断", repairTime: 3, repairCost: 50 });
ok("S4: register ok", r1.ok === true);
ok("S5: register placeId", r1.placeId === "北道");
var r2 = WA.aftermath.register({ placeId: "北道", eventId: "evt_001", effectType: "damage" });
ok("S6: duplicate-event reject", r2.ok === false && r2.reason === "duplicate-event");
var rp1 = WA.aftermath.repair(r1.id, { progress: 1 });
ok("S7: repair partial", rp1.ok === true && rp1.progress === 1);
var rp2 = WA.aftermath.repair(r1.id, { progress: 2 });
ok("S8: repair done", rp2.ok === true && rp2.repaired === true);
var ins = WA.aftermath.inspect("北道");
ok("S9: inspect ok", ins.ok === true && ins.placeId === "北道");
ok("S10: inspect has history", ins.historyCount >= 1);
var act = WA.aftermath.active();
ok("S11: active ok", act.ok === true);
var v1 = WA.aftermath.view(r1.id);
ok("S12: view ok", v1.ok === true && v1.status === "repaired");
var r3 = WA.aftermath.register({ placeId: "南门", eventId: "evt_002", effectType: "blockage" });
var cn = WA.aftermath.cancel(r3.id, "自然恢复");
ok("S13: cancel ok", cn.ok === true && cn.id === r3.id);
console.log("\nTX8 smoke: " + pass + " / " + fail);
process.exit(fail > 0 ? 1 : 0);
