"use strict";
const path = require("path");
process.chdir(path.resolve(__dirname, ".."));
const sync = require("../tests/ui-gate-sync.js");
var boot = sync.fresh({});
var WA = boot.WA;
var pass = 0, fail = 0;
function ok(name, cond) { if (cond) { pass++; } else { fail++; console.log("FAIL: " + name); } }
WA.operations.setSettings({ enabled: true });
WA.inst.setSettings({ enabled: true });
WA.org.setSettings({ enabled: true });
WA.inst.charter("org1", { kind: "\u516c\u53f8" });
WA.inst.post("org1", "r", { perms: ["approve"] });
WA.inst.assign("org1", "r", "p1");
var pr = WA.inst.propose("org1", "\u5efa\u8def\u63d0\u6848", { by: "p1" });
WA.inst.approve("org1", pr.id, { by: "p1" });
ok("S1: operations loaded", typeof WA.operations === "object");
ok("S2: 14 exports", ["getSettings","setSettings","enact","disburse","settle","handover","active","pending","view","cancel","buildBlock","diagnose","stat","reset"].every(function (k) { return typeof WA.operations[k] === "function"; }));
ok("S3: enabled true", WA.operations.getSettings().enabled === true);
var e2 = WA.operations.enact(pr.id, { orgId: "org1", approver: "p1", name: "\u5efa\u8def", budget: 100, milestones: [{ label: "\u52d8\u63a2" }, { label: "\u65bd\u5de5" }, { label: "\u5b8c\u5de5" }] });
ok("S4: enact ok", e2.ok === true);
var dp = WA.operations.disburse(e2.id, { amount: 30, purpose: "\u91c7\u8d2d\u77f3\u6599" });
ok("S5: disburse ok", dp.ok === true);
var st1 = WA.operations.settle(e2.id, { cycleTag: "c1", milestoneIdx: 0 });
ok("S6: settle milestone 0", st1.ok === true && st1.milestoneDone === true);
var st2 = WA.operations.settle(e2.id, { cycleTag: "c2", milestoneIdx: 1 });
ok("S7: settle milestone 1", st2.ok === true && st2.completedMilestones === 2);
var st3 = WA.operations.settle(e2.id, { cycleTag: "c3", milestoneIdx: 2 });
ok("S8: settle complete", st3.ok === true && st3.status === "completed");
var dup = WA.operations.settle(e2.id, { cycleTag: "c3", milestoneIdx: 2 });
ok("S9: completed project reject", dup.ok === false);
var e3 = WA.operations.enact(pr.id, { orgId: "org1", approver: "p1" });
ok("S10: duplicate-enact reject", e3.ok === false && e3.reason === "duplicate-enact");
var act = WA.operations.active();
ok("S11: active ok", act.ok === true);
var pn = WA.operations.pending();
ok("S12: pending ok", pn.ok === true);
var v1 = WA.operations.view(e2.id);
ok("S13: view ok", v1.ok === true && v1.status === "completed");
var dg = WA.operations.diagnose();
ok("S14: diagnose ok", dg.ok === true && dg.closedLoop === true);
var stat = WA.operations.stat();
ok("S15: stat ok", stat.enacted >= 1 && stat.disbursed >= 1);
var bb = WA.operations.buildBlock();
ok("S16: buildBlock string", typeof bb === "string");
console.log("\nTX9 smoke: " + pass + " / " + fail);
process.exit(fail > 0 ? 1 : 0);
